epipeline {
    agent any

    //options {
    //    skipDefaultCheckout true
    //}
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        //Useless
        //GITHUB_ACCESS_KEY_ID  = credentials('jenkins-github-secret-key-id')
        //GITHUB_SECRET_ACCESS_KEY = credentials('jenkins-github-secret-access-key')
        AWS_DEFAULT_REGION="eu-west-3"
        AWS_ECR_URI="987924616652.dkr.ecr.eu-west-2.amazonaws.com/nginx-web-server"
        MSRP_SERVICE="msrp-web-service"
        MSRP_CLUSTER="MSRWEBAPP"
    }
   stages {
        stage('Init'){
            steps{
                sh """#!/bin/bash
                      chmod +x service_manager.sh
                      ./service_manager.sh ${MSRP_SERVICE} ${MSRP_CLUSTER}
                   """
            }
        }
   }
}