FROM alpine:latest

WORKDIR app/

RUN apk add --no-cache \
        python3 \
        py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir \
        awscli \
    && rm -rf /var/cache/apk/*


RUN apk add --no-cache make

RUN apk add --update docker openrc

#RUN service docker start
RUN mkdir /.docker
RUN touch /.docker/config.json
RUN chown -R root /.docker

RUN echo '{"credsStore": "osxkeychain"}' > /.docker/config.json

RUN git clone https://github.com/docker/docker-credential-helpers.git
RUN cd docker-credential-helpers \
    && make osxkeychain \
    && cp bin/build/docker-credential-osxkeychain /usr/local/bin/


