FROM alpine:latest

WORKDIR app/

RUN apk update -y
RUN apk upgrade -y

RUN apk add --no-cache \
        python3 \
        py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir \
        awscli \
    && rm -rf /var/cache/apk/*


RUN apk add --no-cache make


